Kohi-den/extensions-source

src/pt/animesgratis/build.gradle
src/pt/animesgratis/src/eu/kanade/tachiyomi/animeextension/pt/animesgratis/Bakashi.kt

fix(pt/animesgratis): Fixed episode parser for films

---

src/fr/franime/build.gradle
src/fr/franime/src/eu/kanade/tachiyomi/animeextension/fr/franime/dto/FrAnimeDto.kt

Not the best fix but it counts
Closes #74

FRAnime: JSON title is missing fix

---

src/en/nineanime/build.gradle
src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/Aniwave.kt

Enabled/Disabled hoster preferences will be reset due to their name changes.
Closes #89

Aniwave: Empty video list issue solution

---

lib-multisrc/anilist/build.gradle.kts
lib-multisrc/anilist/src/eu/kanade/tachiyomi/multisrc/anilist/AniListAnimeHttpSource.kt
lib-multisrc/anilist/src/eu/kanade/tachiyomi/multisrc/anilist/AniListRequest.kt
lib-multisrc/anilist/src/eu/kanade/tachiyomi/multisrc/anilist/AniListResponse.kt

This module can be used for sources that relies on AniList API for the anime catalog like AniPlay or Dantotsu.
Checklist:

Implement AniList multi source

---

src/pt/otakuanimes/build.gradle
src/pt/otakuanimes/src/eu/kanade/tachiyomi/animeextension/pt/otakuanimes/OtakuAnimes.kt

fix(pt/otakuanimes): Fixed images on search for pt/otakuanimes

---

src/all/torrentioanime/build.gradle
src/all/torrentioanime/src/eu/kanade/tachiyomi/animeextension/all/torrentioanime/Torrentio.kt

The episode list for the wrong anime was returned by the old url. This patch fixes that by specifically using the kitsu id instead.
Demo (at the time of this PR):
Actual Anilist ID: 166531
Corresponding Kitsu ID: 47659
Wrong metadata: <https://anime-kitsu.strem.fun/meta/series/anilist%3A166531.json>
Correct metadata: <https://anime-kitsu.strem.fun/meta/series/kitsu%3A47659.json>
Checklist:

fix(all/torrentioanime): Fix fetching episode list

---

gradle/libs.versions.toml

I have posted this issue on aniyomi [Ref](https://github.com/aniyomiorg/aniyomi/issues/1776)
and to fix the problem [Ref](https://github.com/mihonapp/mihon/commit/83fd4746eda1b99f35292b0c2211e606a421b3eb)
Checklist:

fix(deps): change dependency inorichi.injekt to mihonapp:injekt

---

src/pt/anitube/build.gradle
src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/Anitube.kt
src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/extractors/AnitubeDownloadExtractor.kt

Sometimes, the file4go have a strong cloudflare protection.
With disabled option, the fetch videos vill be faster.
Checklist:

fix(pt/Anitube): Added option to disable File4Go mirror

---

src/zh/xfani/build.gradle
src/zh/xfani/src/eu/kanade/tachiyomi/animeextension/zh/xfani/Xfani.kt

After the website updated its SSL certificate, there are certificate verification issues on mobile devices. Add an option to ignore SSL verification.
Checklist:

Xfani：add new preference to ignore ssl verify issue.

---

src/all/torrentioanime/build.gradle
src/all/torrentioanime/src/eu/kanade/tachiyomi/animeextension/all/torrentioanime/Torrentio.kt
src/all/torrentioanime/src/eu/kanade/tachiyomi/animeextension/all/torrentioanime/dto/TorrentioDto.kt

This patch makes the extension ignore episodes that are in the URL but still unreleased.
Checklist:

Ignore episodes without video list

---

src/en/dramacool/build.gradle
src/en/dramacool/src/eu/kanade/tachiyomi/animeextension/en/dramacool/DramaCool.kt

Fix DramaCool source

---

lib-multisrc/zorotheme/build.gradle.kts
lib-multisrc/zorotheme/src/eu/kanade/tachiyomi/multisrc/zorotheme/ZoroTheme.kt
src/en/zoro/build.gradle
src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/HiAnime.kt

Close #380 
Tested on kaido too as both use ZoroTheme, though I don't see any issue reported for it.
Also override ZoroTheme's default endpoint for latest update in HiAnime from `/top-airing` into `/recently-updated`, which is more appropriate. Kaido will keep using the default in case others preferred that.
Checklist:

Fix HiAnime pref quality

---

src/all/sudatchi/build.gradle
src/all/sudatchi/src/eu/kanade/tachiyomi/animeextension/all/sudatchi/Sudatchi.kt

Close #348 
After testing it locally the subtitles now properly load, however this is my first pull request here so excuse me if I did anything wrong , thanks.
Checklist:

fix(all/sudatchi): fix sudatchi subtitles

---

src/all/hikari/build.gradle
src/all/hikari/src/eu/kanade/tachiyomi/animeextension/all/hikari/Hikari.kt

The main problem is the Chillx extractor, that doesn't work.
The sollution is return the result of others extractors.
Checklist:

fix(all/hiraki): Partial fix for Hikari source

---

src/zh/xfani/build.gradle
src/zh/xfani/src/eu/kanade/tachiyomi/animeextension/zh/xfani/Xfani.kt

Due to the possibility of inconsistent episode counts across different server, it has been modified to first match based on names and allowing for the presence of missing entries.
Checklist:

Xfani: Fix video list parse

---

lib/vidguard-extractor/src/main/java/eu/kanade/tachiyomi/lib/vidguardextractor/VidGuardExtractor.kt

fix(lib/VidGuardExtractor): Increase stack size to 8MB

---

src/it/animesaturn/build.gradle
src/it/animesaturn/src/eu/kanade/tachiyomi/animeextension/it/animesaturn/AnimeSaturn.kt

Checklist:
I've left the old domain as an option. All of the available domains can be found at https://www.animesaturn.me/

fix(it/animesaturn): Domain update for AnimeSaturn

---

src/en/aniplay/build.gradle
src/en/aniplay/src/eu/kanade/tachiyomi/animeextension/en/aniplay/AniPlay.kt
src/en/aniplay/src/eu/kanade/tachiyomi/animeextension/en/aniplay/AniPlayDto.kt

Checklist:
Closes #588
Pahe provider videos shows as "Video" quality.
This is from 
```
return playlistUtils.extractFromHls(
playlistUrl = defaultSource.url,
videoNameGen = { quality -> "$serverName - $quality - $typeName" },
subtitleList = subtitles,
)
```
and I kind of dont care. It works.

feat(en/aniplay): new provider pahe implemented (somewhat)

---

lib/playlist-utils/src/main/java/eu/kanade/tachiyomi/lib/playlistutils/PlaylistUtils.kt
src/all/missav/build.gradle

MissAv: Fix hls parsing error

---

src/zh/hanime1/build.gradle
src/zh/hanime1/src/eu/kanade/tachiyomi/animeextension/zh/hanime1/Hanime1.kt

Some small fix:
* Filter ads from search results
* Fix the issue that some videos can't find their source
* Add a new preference to select the preferred language for subtitles
Checklist:

Hanime1: Filter ads from search results and more

---

src/en/aniplay/build.gradle
src/en/aniplay/src/eu/kanade/tachiyomi/animeextension/en/aniplay/AniPlay.kt

Close #855 
If this happens again I will need to find a way to get them automatically.
Checklist:

fix(en/Aniplay): new headers (again)

---

.github/workflows/build_push.yml

Updated Validate Gradle Wrapper job from `build_push.yml` to new version.
Maybe this will solve failed runs. [example failed run](https://github.com/Kohi-den/extensions-source/actions/runs/14167793031/job/39684667322)
If not it is at least on new version.

ci(build_push): updated Validate Gradle Wrapper

---

src/en/animepahe/build.gradle
src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt
src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/HiAnime.kt

Checklist:
**Problem:**  
Previously, the app directly relied on the episode numbers returned by AnimePahe's backend. This caused issues in cases where series had multiple seasons or non-standard episode numbering (e.g., a second season starting at episode 25). As a result, the app would incorrectly match new episodes (like episode 25 of season 2) with existing entries, leading to inaccurate updates and metadata.
**Fix:**  
Modified the `episodeListParse` logic to:
- Extract all episodes via the `recursivePages` function.
- Sort episodes chronologically using the `date_upload` timestamp to ensure correct order.
- Reassign episode numbers locally using the list index, so episode 1 of any series is labeled as Episode 1, regardless of its original number in AnimePahe's API.
- Generate …

Fix AnimePahe episode sorting and numbering logic

---

src/all/torrentioanime/build.gradle
src/all/torrentioanime/src/eu/kanade/tachiyomi/animeextension/all/torrentioanime/Torrentio.kt

(all/torrentioanime) Fixing Some episode not shown due to ONA and OVA class

---

lib/buzzheavier-extractor/src/main/java/eu/kanade/tachiyomi/lib/buzzheavierextractor/BuzzheavierExtractor.kt
src/all/hikari/build.gradle
src/all/hikari/src/eu/kanade/tachiyomi/animeextension/all/hikari/Dto.kt
src/all/hikari/src/eu/kanade/tachiyomi/animeextension/all/hikari/Hikari.kt

Update hikari with minor fixes. Buzzheavier extractor less prone to failure.
