Kohi-den/extensions-source

.github/scripts/commit-repo.sh
.github/workflows/build_push.yml

ci: Fixed pusblish script

---

.github/scripts/bump-versions.py
.github/scripts/commit-repo.sh
.github/workflows/build_push.yml

chore: Updated build_push.yml

---

src/pt/animeq/AndroidManifest.xml
src/pt/animeq/build.gradle
src/pt/animeq/src/eu/kanade/tachiyomi/animeextension/pt/animeq/AnimeQ.kt
src/pt/animeq/src/eu/kanade/tachiyomi/animeextension/pt/animeq/AnimeQUrlActivity.kt
src/pt/animeszone/AndroidManifest.xml
src/pt/animeszone/build.gradle
src/pt/animeszone/src/eu/kanade/tachiyomi/animeextension/pt/animeszone/AZUrlActivity.kt
src/pt/animeszone/src/eu/kanade/tachiyomi/animeextension/pt/animeszone/AnimesZone.kt
src/pt/anitube/AndroidManifest.xml
src/pt/anitube/build.gradle
src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/Anitube.kt
src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/AnitubeUrlActivity.kt

Added support to Url Activity

---

src/fr/anisama/build.gradle
src/fr/anisama/src/eu/kanade/tachiyomi/animeextension/fr/anisama/AniSama.kt

Fix anime sama

---

src/id/animeindo/build.gradle
src/id/animeindo/src/eu/kanade/tachiyomi/animeextension/id/animeindo/AnimeIndo.kt
src/id/kuramanime/build.gradle
src/id/kuramanime/src/eu/kanade/tachiyomi/animeextension/id/kuramanime/Kuramanime.kt

fix(id/kuramanime & animeindo): Update baseUrl & Fix http 404 error

---

src/pt/animeplayer/build.gradle
src/pt/animeplayer/src/eu/kanade/tachiyomi/animeextension/pt/animeplayer/AnimePlayer.kt

fix(pt/animeplayer): Fixed video list for pt/AnimePlayer

---

src/it/animeworld/build.gradle
src/it/animeworld/src/eu/kanade/tachiyomi/animeextension/it/animeworld/ANIMEWORLD.kt

[IT] Gradle Update + Anime World Fix

---

src/fr/nekosama/build.gradle
src/fr/nekosama/src/eu/kanade/tachiyomi/animeextension/fr/nekosama/NekoSama.kt

Gradle Update + NekoSama Fix

---

src/id/oploverz/build.gradle
src/id/oploverz/src/eu/kanade/tachiyomi/animeextension/id/oploverz/Oploverz.kt
src/id/samehadaku/build.gradle
src/id/samehadaku/src/eu/kanade/tachiyomi/animeextension/id/samehadaku/Samehadaku.kt

fix(id/samehadaku & oploverz): Update baseUrl

---

src/ar/anime4up/build.gradle
src/ar/anime4up/src/eu/kanade/tachiyomi/animeextension/ar/anime4up/Anime4Up.kt
src/es/hackstore/build.gradle
src/es/hackstore/src/eu/kanade/tachiyomi/animeextension/es/hackstore/Hackstore.kt

chore(src/es and ar)  Fix Hackstore and  Anime4up

---

src/id/minioppai/build.gradle
src/id/minioppai/src/eu/kanade/tachiyomi/animeextension/id/minioppai/MiniOppai.kt

fix(id/minioppai): Update baseUrl

---

src/es/animeonlineninja/build.gradle
src/es/animeonlineninja/src/eu/kanade/tachiyomi/animeextension/es/animeonlineninja/AnimeOnlineNinja.kt

Feat(es/AnimeOnline.Ninja): add select server in settings

---

src/en/nineanime/build.gradle
src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/Aniwave.kt
src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/AniwaveUtils.kt

Added custom key system with preferences and changed default keys
Closes #56

Aniwave updated keys and custom keys option

---

src/en/nineanime/build.gradle
src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/Aniwave.kt

Aniwave updates

---

src/en/nineanime/build.gradle
src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/Aniwave.kt

Reverts almightyhak/aniyomi-extensions#98

Revert "Aniwave updates"

---

lib/vidsrc-extractor/src/main/java/eu/kanade/tachiyomi/lib/vidsrcextractor/VidSrcExtractor.kt
src/en/nineanime/build.gradle
src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/Aniwave.kt

Fix Aniwave Vidstream & MegaF sources

---

lib-multisrc/anilist/build.gradle.kts
lib-multisrc/anilist/src/eu/kanade/tachiyomi/multisrc/anilist/AniListAnimeHttpSource.kt
src/en/aniplay/build.gradle

Fix AniPlay titles

---

lib/dood-extractor/src/main/java/eu/kanade/tachiyomi/lib/doodextractor/DoodExtractor.kt
src/es/cuevana/build.gradle
src/es/cuevana/src/eu/kanade/tachiyomi/animeextension/es/cuevana/CuevanaEu.kt
src/es/metroseries/build.gradle
src/es/metroseries/src/eu/kanade/tachiyomi/animeextension/es/metroseries/MetroSeries.kt
src/es/pelisplushd/build.gradle
src/es/pelisplushd/src/eu/kanade/tachiyomi/animeextension/es/pelisplushd/Pelisplushd.kt
src/es/pelisplushd/src/eu/kanade/tachiyomi/animeextension/es/pelisplushd/Pelisplusto.kt

Spanish extension fixes

---

lib/streamwish-extractor/src/main/java/eu/kanade/tachiyomi/lib/streamwishextractor/StreamWishExtractor.kt

chore(lib/StreamWishExtractor): Update StreamWishExtractor

---

lib/vidhide-extractor/src/main/java/eu/kanade/tachiyomi/lib/vidhideextractor/JsUnpacker.kt
lib/vidhide-extractor/src/main/java/eu/kanade/tachiyomi/lib/vidhideextractor/VidHideExtractor.kt

Fix(lib/VidHideExtractor)

---

src/pt/anitube/build.gradle
src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/Anitube.kt
src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/extractors/AnitubeExtractor.kt

fix(pt/anitube): Fixed pt/Anitube sources (fix #141)

---

src/all/hikari/build.gradle
src/all/hikari/src/eu/kanade/tachiyomi/animeextension/all/hikari/Hikari.kt

Feat(all/Hikari): identify Sub or Dub

---

src/en/nineanime/build.gradle
src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/Aniwave.kt
src/en/nineanime/src/eu/kanade/tachiyomi/animeextension/en/nineanime/AniwaveUtils.kt

Fix(en/Aniwave): fix encryption

---

src/all/hikari/build.gradle
src/all/hikari/src/eu/kanade/tachiyomi/animeextension/all/hikari/Hikari.kt

Fix(en/Hikari): The sub or dub fix has been modified

---

src/pt/anitube/build.gradle
src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/Anitube.kt
src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/extractors/AnitubeExtractor.kt
src/pt/hinatasoul/build.gradle
src/pt/hinatasoul/src/eu/kanade/tachiyomi/animeextension/pt/hinatasoul/HinataSoul.kt
src/pt/hinatasoul/src/eu/kanade/tachiyomi/animeextension/pt/hinatasoul/extractors/HinataSoulExtractor.kt

fix(pt/anitube): Fixed pt/Anitube and pt/HinataSoul sources

---

src/it/toonitalia/build.gradle
src/it/toonitalia/src/eu/kanade/tachiyomi/animeextension/it/toonitalia/Toonitalia.kt

Fix(it/Toonitalia): Fixed video empty list

---

lib/chillx-extractor/src/main/java/eu/kanade/tachiyomi/lib/chillxextractor/ChillxExtractor.kt
src/en/tokuzilla/build.gradle
src/hi/animesaga/build.gradle

Fix(lib/ChillxExtractor): Unify extraction logic, improve key fetching and subtitle handling

---

src/pt/anitube/build.gradle
src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/Anitube.kt
src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/extractors/AnitubeExtractor.kt
src/pt/hinatasoul/build.gradle
src/pt/hinatasoul/src/eu/kanade/tachiyomi/animeextension/pt/hinatasoul/HinataSoul.kt
src/pt/hinatasoul/src/eu/kanade/tachiyomi/animeextension/pt/hinatasoul/extractors/HinataSoulExtractor.kt

fix(pt/anitube): Fixed pt/Anitube and pt/HinataSoul sources again

---

src/pt/animesgames/build.gradle
src/pt/animesgames/src/eu/kanade/tachiyomi/animeextension/pt/animesgames/AnimesGames.kt

fix(pt/animesgames): Fixed pt/AnimesGames images

---

src/pt/anitube/build.gradle
src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/Anitube.kt
src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/extractors/AnitubeDownloadExtractor.kt
src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/extractors/AnitubeExtractor.kt
src/pt/hinatasoul/build.gradle
src/pt/hinatasoul/src/eu/kanade/tachiyomi/animeextension/pt/hinatasoul/HinataSoul.kt
src/pt/hinatasoul/src/eu/kanade/tachiyomi/animeextension/pt/hinatasoul/extractors/HinataSoulDownloadExtractor.kt
src/pt/hinatasoul/src/eu/kanade/tachiyomi/animeextension/pt/hinatasoul/extractors/HinataSoulExtractor.kt

fix(pt/anitube): Fixed Anitube and HinataSoul for old videos (fix #182)

---

lib-multisrc/anilist/build.gradle.kts
lib-multisrc/anilist/src/eu/kanade/tachiyomi/multisrc/anilist/AniListAnimeHttpSource.kt
lib-multisrc/anilist/src/eu/kanade/tachiyomi/multisrc/anilist/AniListFilters.kt
lib-multisrc/anilist/src/eu/kanade/tachiyomi/multisrc/anilist/AniListRequest.kt
lib-multisrc/anilist/src/eu/kanade/tachiyomi/multisrc/anilist/AniListResponse.kt
src/en/aniplay/build.gradle
src/en/aniplay/src/eu/kanade/tachiyomi/animeextension/en/aniplay/AniPlay.kt
src/en/aniplay/src/eu/kanade/tachiyomi/animeextension/en/aniplay/AniPlayDto.kt

Fix(en/AniPlay): Update source

---

src/en/allanime/build.gradle
src/en/allanime/src/eu/kanade/tachiyomi/animeextension/en/allanime/AllAnime.kt

Closes #83
Closes #84
Checklist:

chore(src/en): AllAnime video extractor improvements

---

src/pt/betteranime/build.gradle
src/pt/betteranime/src/eu/kanade/tachiyomi/animeextension/pt/betteranime/LoginInterceptor.kt

fix(pt/betteranime): Fixed pt/BetterAnime source (fix #222)

---

.github/ISSUE_TEMPLATE/01_report_issue.yml
.github/ISSUE_TEMPLATE/02_request_source.yml
.github/ISSUE_TEMPLATE/06_request_meta.yml
.github/ISSUE_TEMPLATE/07_request_removal.yml
.github/ISSUE_TEMPLATE/config.yml

Reverts Kohi-den/extensions-source#234

Revert "updated issue temples"

---

src/pt/animesroll/build.gradle
src/pt/animesroll/src/eu/kanade/tachiyomi/animeextension/pt/animesroll/AnimesROLL.kt
src/pt/animesroll/src/eu/kanade/tachiyomi/animeextension/pt/animesroll/dto/AnimesROLLDto.kt

fix(pt/animesroll): Fixed pt/AnimesROLL source (fix #225)

---

src/en/animeowl/build.gradle
src/en/animeowl/src/eu/kanade/tachiyomi/animeextension/en/animeowl/AnimeOwl.kt
src/en/animeowl/src/eu/kanade/tachiyomi/animeextension/en/animeowl/AnimeOwlDto.kt
src/en/animeowl/src/eu/kanade/tachiyomi/animeextension/en/animeowl/extractors/OwlExtractor.kt

fix(src/en): Fix AnimeOwl

---

src/pt/megaflix/build.gradle
src/pt/megaflix/src/eu/kanade/tachiyomi/animeextension/pt/megaflix/Megaflix.kt

fix(src/pt): Megaflix fixed

---

lib/chillx-extractor/src/main/java/eu/kanade/tachiyomi/lib/chillxextractor/ChillxExtractor.kt
src/all/hikari/build.gradle
src/all/hikari/src/eu/kanade/tachiyomi/animeextension/all/hikari/Hikari.kt

Feat(lib/ChillxExtractor): Update extractor and add extractor to Hikari

---

src/id/otakudesu/build.gradle
src/id/otakudesu/src/eu/kanade/tachiyomi/animeextension/id/otakudesu/OtakuDesu.kt

Feat(id/OtakuDesu): add hidevid extractor

---

src/de/filmpalast/build.gradle
src/de/filmpalast/src/eu/kanade/tachiyomi/animeextension/de/filmpalast/FilmPalast.kt

Fix(de/FilmPalast): Fix process extractor

---

src/en/pinoymoviepedia/src/eu/kanade/tachiyomi/animeextension/en/pinoymoviepedia/PinoyMoviePedia.kt
src/en/pinoymoviepedia/src/eu/kanade/tachiyomi/animeextension/en/pinoymoviepedia/PinoyMoviePediaFilters.kt

fix Pinoymoviepedia

---

lib/chillx-extractor/src/main/java/eu/kanade/tachiyomi/lib/chillxextractor/ChillxExtractor.kt
src/all/hikari/src/eu/kanade/tachiyomi/animeextension/all/hikari/Hikari.kt

Fix(lib/ChillxExtractor): update Referer

---

lib/chillx-extractor/src/main/java/eu/kanade/tachiyomi/lib/chillxextractor/ChillxExtractor.kt
src/all/hikari/src/eu/kanade/tachiyomi/animeextension/all/hikari/Hikari.kt

Hikari fix

---

src/es/animeonlineninja/build.gradle
src/es/animeonlineninja/src/eu/kanade/tachiyomi/animeextension/es/animeonlineninja/AnimeOnlineNinja.kt

fix(src/es): AnimeOnlineNinja - Improvements and fixes

---

lib-multisrc/zorotheme/src/eu/kanade/tachiyomi/multisrc/zorotheme/ZoroTheme.kt
src/en/zoro/build.gradle

Feat(en/HiAnime): Support Raw servers

---

src/es/animefenix/build.gradle
src/es/animefenix/src/eu/kanade/tachiyomi/animeextension/es/animefenix/Animefenix.kt

Fix(es/Animefenix): fix empty list by bapeey

---

src/hi/yomovies/build.gradle
src/hi/yomovies/src/eu/kanade/tachiyomi/animeextension/hi/yomovies/YoMovies.kt

Fix(hi/YoMovies): Update source

---

src/pt/megaflix/build.gradle
src/pt/megaflix/src/eu/kanade/tachiyomi/animeextension/pt/megaflix/Megaflix.kt
src/pt/megaflix/src/eu/kanade/tachiyomi/animeextension/pt/megaflix/MegaflixUrlActivity.kt
src/pt/megaflix/src/eu/kanade/tachiyomi/animeextension/pt/megaflix/WebViewResolver.kt
src/pt/megaflix/src/eu/kanade/tachiyomi/animeextension/pt/megaflix/extractors/MegaflixExtractor.kt

fix(pt/megaflix): Fixed pt/MegaFlix source

---

src/es/animefenix/build.gradle
src/es/animefenix/src/eu/kanade/tachiyomi/animeextension/es/animefenix/AnimeFenixFilters.kt
src/es/animefenix/src/eu/kanade/tachiyomi/animeextension/es/animefenix/Animefenix.kt

Checklist:
This fixes AnimeFenix and organize the magic values in objects to easily update

Fix(es/AnimeFenix): Fix AnimeFenix

---

src/zh/xfani/build.gradle
src/zh/xfani/src/eu/kanade/tachiyomi/animeextension/zh/xfani/Filters.kt
src/zh/xfani/src/eu/kanade/tachiyomi/animeextension/zh/xfani/Xfani.kt

1. Fix bug that set filter will give empty result.
2. Support video source list
Checklist:

xfani: fix filter error

---

src/pt/rinecloud/build.gradle
src/pt/rinecloud/src/eu/kanade/tachiyomi/animeextension/pt/rinecloud/extractors/RineCloudExtractor.kt

pt/rinecloud: Fixed pt/RineCloud source (fix #327)

---

src/zh/hanime1/build.gradle
src/zh/hanime1/src/eu/kanade/tachiyomi/animeextension/zh/hanime1/Hanime1.kt

Hanime1.me: Fix tags filter

---

src/tr/hentaizm/build.gradle
src/tr/hentaizm/src/eu/kanade/tachiyomi/animeextension/tr/hentaizm/HentaiZM.kt

Hentai zm turc

---

lib/bangumi-scraper/build.gradle.kts
lib/bangumi-scraper/src/main/java/eu/kanade/tachiyomi/lib/bangumiscraper/BangumiDTO.kt
lib/bangumi-scraper/src/main/java/eu/kanade/tachiyomi/lib/bangumiscraper/BangumiScraper.kt
lib/bangumi-scraper/src/main/java/eu/kanade/tachiyomi/lib/bangumiscraper/BangumiScraperException.kt
src/zh/anime1/build.gradle
src/zh/anime1/src/eu/kanade/tachiyomi/animeextension/zh/anime1/Anime1.kt

Anime1.me(zh/hant): Fetch anime detail from bangumi.

---

src/pt/vizer/build.gradle
src/pt/vizer/src/eu/kanade/tachiyomi/animeextension/pt/vizer/Vizer.kt
src/pt/vizer/src/eu/kanade/tachiyomi/animeextension/pt/vizer/VizerFilters.kt

fix(pt/Vizer): Fixed max year and empty video list

---

src/en/aniplay/build.gradle
src/en/aniplay/src/eu/kanade/tachiyomi/animeextension/en/aniplay/AniPlay.kt

Closes #405
Closes #406
Checklist:

 Fix(en/Aniplay): Fixed video list is empty and fixed unresolved host issue

---

src/es/homecine/build.gradle
src/es/homecine/src/eu/kanade/tachiyomi/animeextension/es/homecine/HomeCine.kt
src/es/metroseries/build.gradle
src/es/metroseries/src/eu/kanade/tachiyomi/animeextension/es/metroseries/MetroSeries.kt
src/es/pelisforte/build.gradle
src/es/pelisforte/src/eu/kanade/tachiyomi/animeextension/es/pelisforte/PelisForte.kt

Checklist:
Closes #370
Closes #384
Closes #411

Fix(src/es): Pelisforte, HomeCine and MetroSeries fixes

---

src/en/aniplay/build.gradle
src/en/aniplay/src/eu/kanade/tachiyomi/animeextension/en/aniplay/AniPlay.kt
src/en/aniplay/src/eu/kanade/tachiyomi/animeextension/en/aniplay/AniPlayDto.kt

Closes #434
Closes #356
Checklist:

fix: Aniplay 

---

src/en/rule34video/build.gradle
src/en/rule34video/src/eu/kanade/tachiyomi/animeextension/en/rule34video/Rule34Video.kt

Fix loading video details and add setting to filter videos by uploader ID.
Checklist:

feat(en/rule34video): Update Source: en/rule34video

---

src/all/jable/build.gradle
src/all/jable/src/eu/kanade/tachiyomi/animeextension/all/jable/Jable.kt
src/all/jable/src/eu/kanade/tachiyomi/animeextension/all/jable/JableFactory.kt
src/all/jable/src/eu/kanade/tachiyomi/animeextension/all/jable/JableIntl.kt

Correct the language code and fix the issue of only one page loading.
Checklist:

Jable: Correct the language code and fix page load issue.

---

src/tr/hentaizm/build.gradle
src/tr/hentaizm/src/eu/kanade/tachiyomi/animeextension/tr/hentaizm/HentaiZM.kt

fix: Fixed extension publish

---

src/de/serienstream/build.gradle
src/de/serienstream/src/eu/kanade/tachiyomi/animeextension/de/serienstream/Serienstream.kt

Changed ip adress to url
Sorry, is my first pull request
Checklist:

Update Serienstream.kt from ip adress to url. (For https)

---

src/pt/anitube/build.gradle
src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/extractors/AnitubeExtractor.kt

fix(pt/anitube): Fixed pt/Anitube source (fix #469,#494)

---

lib/streamwish-extractor/src/main/java/eu/kanade/tachiyomi/lib/streamwishextractor/StreamWishExtractor.kt
src/es/jkanime/build.gradle
src/es/jkanime/src/eu/kanade/tachiyomi/animeextension/es/jkanime/Jkanime.kt

fix(src/es): JkAnime fixes

---

src/all/animexin/build.gradle
src/all/animexin/src/eu/kanade/tachiyomi/animeextension/all/animexin/AnimeXin.kt

Close #493 
Close #251 
Close #467 
Close #449 
Checklist:

AnimeXin: update url

---

src/all/missav/build.gradle
src/all/missav/src/eu/kanade/tachiyomi/animeextension/all/missav/MissAV.kt

Checklist:
https://github.com/Kohi-den/extensions-source/issues/523

fix(all/missav): Domain update for MissAV

---

src/tr/tranimeizle/AndroidManifest.xml
src/tr/tranimeizle/build.gradle
src/tr/tranimeizle/src/eu/kanade/tachiyomi/animeextension/tr/tranimeizle/TRAnimeIzle.kt
src/tr/tranimeizle/src/eu/kanade/tachiyomi/animeextension/tr/tranimeizle/TRAnimeIzleUrlActivity.kt

fix(tr/tranimeizle): Domain update for tranimeizle

---

src/en/animepahe/build.gradle
src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt
src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/KwikExtractor.kt
src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/dto/AnimePaheDto.kt

This PR closes issue #550 and improved the KwikExtractor Decrypt Function.
Upon looking into the decrypt function in KwikExtractor, I noticed that it was one of the contributing factors that makes the video loading slow. After analysing the decryption routine, I noticed the `getString` function can be replaced with `toInt` function since the `getString` function is basically a Base N to Decimal Converter.

Fix #550 and Improve KwikExtractor Decrypt Function

---

src/pt/anitube/build.gradle
src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/extractors/AnitubeExtractor.kt

fix(pt/anitube): Fixed pt/Anitube (close #525)

---

src/all/subsplease/build.gradle
src/all/subsplease/src/eu/kanade/tachiyomi/animeextension/all/subsplease/Subsplease.kt

Checklist:
**torrentio** api is used to impelement the debrid support. only the real-debrid is tested, but should work with all of them.

feat(all/subsplease): debrid support for all/Subsplease

---

src/all/subsplease/build.gradle
src/all/subsplease/src/eu/kanade/tachiyomi/animeextension/all/subsplease/Subsplease.kt

fix(all/subsplease): Fixed error for special episode numbers for all/Subsplease

---

src/it/animeworld/build.gradle
src/it/animeworld/src/eu/kanade/tachiyomi/animeextension/it/animeworld/ANIMEWORLD.kt

Closes: #578 
Checklist:
* Added `token` and `lastTokenRefresh` variables for managing cookies.
* Implemented `extractCookie` method to extract cookie values from HTML.
* Implemented `localGet` method to handle HTTP requests with cookies, refreshing the token if necessary.

Animeworld 202 fix

---

src/it/animeworld/build.gradle
src/it/animeworld/src/eu/kanade/tachiyomi/animeextension/it/animeworld/ANIMEWORLD.kt
src/it/animeworld/src/eu/kanade/tachiyomi/animeextension/it/animeworld/ShittyRedirectionInterceptor.kt

Checklist:
The app was tested and now works properly on the devices

fix(it/animeworld): 202 redirect proper fix

---

src/en/aniplay/build.gradle
src/en/aniplay/src/eu/kanade/tachiyomi/animeextension/en/aniplay/AniPlay.kt
src/en/aniplay/src/eu/kanade/tachiyomi/animeextension/en/aniplay/AniPlayDto.kt

fix(en/aniplay): Subtitles not working fix

---

src/pt/animesonlinevip/build.gradle
src/pt/animesonlinevip/src/eu/kanade/tachiyomi/animeextension/pt/animesonlinevip/AnimesOnlineVip.kt

fix(pt/animesonlinevip): Updated domain for pt/Animes Online Vip

---

src/zh/hanime1/build.gradle
src/zh/hanime1/src/eu/kanade/tachiyomi/animeextension/zh/hanime1/Filters.kt

Hanime1: Fix popular anime

---

src/it/animeunity/build.gradle
src/it/animeunity/src/eu/kanade/tachiyomi/animeextension/it/animeunity/AnimeUnity.kt
src/it/animeunity/src/eu/kanade/tachiyomi/animeextension/it/animeunity/AnimeUnityFilters.kt

fix(it/animeunity): Fix video streams URLs

---

src/en/aniplay/build.gradle
src/en/aniplay/src/eu/kanade/tachiyomi/animeextension/en/aniplay/AniPlay.kt
src/en/aniplay/src/eu/kanade/tachiyomi/animeextension/en/aniplay/AniPlayDto.kt

Closes #614
Closes #624 - some animes are broken at aniplays site...
Checklist:

fix(en/Aniplay): new server, fixed dub with subtitles showing as softsub, latest fixes

---

src/tr/hentaizm/build.gradle
src/tr/hentaizm/src/eu/kanade/tachiyomi/animeextension/tr/hentaizm/HentaiZM.kt

Fix HentaiM5

---

src/pt/anitube/build.gradle
src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/extractors/AnitubeExtractor.kt

fix(pt/anitube): Fixed pt/Anitube source (fix #695)

---

src/zh/xfani/build.gradle
src/zh/xfani/src/eu/kanade/tachiyomi/animeextension/zh/xfani/Xfani.kt

Xfani: Fix episode list sort

---

src/en/animeowl/build.gradle
src/en/animeowl/src/eu/kanade/tachiyomi/animeextension/en/animeowl/AnimeOwl.kt

(en/animeowl) Updated Url of Animeowl

---

src/all/animeworldindia/build.gradle
src/all/animeworldindia/src/eu/kanade/tachiyomi/animeextension/all/animeworldindia/AnimeWorldIndia.kt
src/all/animeworldindia/src/eu/kanade/tachiyomi/animeextension/all/animeworldindia/AnimeWorldIndiaFilters.kt

(all/animewolrdindia) Changed Url 

---

src/pt/anitube/build.gradle
src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/extractors/AnitubeExtractor.kt

fix(pt/anitube): Fixed pt/Anitube source

---

src/pt/animesgratis/build.gradle
src/pt/animesgratis/src/eu/kanade/tachiyomi/animeextension/pt/animesgratis/Q1N.kt
src/pt/animesgratis/src/eu/kanade/tachiyomi/animeextension/pt/animesgratis/extractors/NoaExtractor.kt
src/pt/animesgratis/src/eu/kanade/tachiyomi/animeextension/pt/animesgratis/extractors/RuplayExtractor.kt

fix(pt/animesgratis): Fixed Q1N video source for MDPLAYER

---

src/en/animeowl/build.gradle
src/en/animeowl/src/eu/kanade/tachiyomi/animeextension/en/animeowl/AnimeOwl.kt
src/en/animeowl/src/eu/kanade/tachiyomi/animeextension/en/animeowl/AnimeOwlDto.kt
src/en/animeowl/src/eu/kanade/tachiyomi/animeextension/en/animeowl/extractors/OwlExtractor.kt

Checklist:
Fixes #199 , #757 , #751 ...

[AnimeOwl] fix: Video list + Episode list

---

src/en/aniplay/build.gradle
src/en/aniplay/src/eu/kanade/tachiyomi/animeextension/en/aniplay/AniPlay.kt

fix(en/Aniplay): New headers and proxy

---

lib/megacloud-extractor/src/main/java/eu/kanade/tachiyomi/lib/megacloudextractor/MegaCloudExtractor.kt

(lib/Megacloud) Updated to new domain from .club to .blog

---

lib-multisrc/anilist/build.gradle.kts
lib-multisrc/anilist/src/eu/kanade/tachiyomi/multisrc/anilist/AniListFilters.kt
lib-multisrc/zorotheme/build.gradle.kts
lib-multisrc/zorotheme/src/eu/kanade/tachiyomi/multisrc/zorotheme/ZoroThemeFilters.kt

Checklist:
Close #627 (Already closed but not done yet)

Added 2025 and 2026 Year Filter for HiAnime and Aniplay 

---

src/en/kickassanime/build.gradle
src/en/kickassanime/src/eu/kanade/tachiyomi/animeextension/en/kickassanime/KickAssAnime.kt

(en/kickassanime) Adding kaa.mx 

---

src/en/animekhor/build.gradle
src/en/animekhor/src/eu/kanade/tachiyomi/animeextension/en/animekhor/AnimeKhor.kt

Domain Change (en/AnimeKhor) .xyz to .org

---

src/en/zoro/build.gradle
src/en/zoro/src/eu/kanade/tachiyomi/animeextension/en/zoro/HiAnime.kt

Checklist:
Close #910 Close #911

(en/zoro) Hianime is back with official Domain changes source link 

---

lib-multisrc/zorotheme/build.gradle.kts
src/en/aniplay/build.gradle

bump aniplay & exts using zorotheme

---

lib-multisrc/dooplay/build.gradle.kts
lib-multisrc/dooplay/src/eu/kanade/tachiyomi/multisrc/dooplay/DooPlay.kt

Added more quality preferences in Dooplay

---

lib/buzzheavier-extractor/src/main/java/eu/kanade/tachiyomi/lib/buzzheavierextractor/BuzzheavierExtractor.kt
src/all/hikari/build.gradle
src/all/hikari/src/eu/kanade/tachiyomi/animeextension/all/hikari/Hikari.kt

hikari: fix buzzheavier

---

src/all/hikari/build.gradle
src/all/hikari/src/eu/kanade/tachiyomi/animeextension/all/hikari/Hikari.kt

(all/hikari) provider selection and hiki mirrors

---

src/en/animepahe/build.gradle
src/en/animepahe/src/eu/kanade/tachiyomi/animeextension/en/animepahe/AnimePahe.kt

AnimePahe: Reverse episode order

---

lib/chillx-extractor/src/main/java/eu/kanade/tachiyomi/lib/chillxextractor/ChillxExtractor.kt
lib/chillx-extractor/src/main/java/eu/kanade/tachiyomi/lib/chillxextractor/WebViewResolver.kt
src/all/hikari/build.gradle
src/en/tokuzilla/build.gradle
src/hi/animesaga/build.gradle

Update chillx extractor

---

src/ar/witanime/build.gradle
src/ar/witanime/src/eu/kanade/tachiyomi/animeextension/ar/witanime/WitAnime.kt

(ar/witanime) Domain Change

---

src/en/aniplay/build.gradle
src/en/aniplay/src/eu/kanade/tachiyomi/animeextension/en/aniplay/AniPlay.kt

fix(Aniplay): changed proxy url 

---

src/pt/anitube/build.gradle
src/pt/anitube/src/eu/kanade/tachiyomi/animeextension/pt/anitube/Anitube.kt

fix(pt/anitube): Fixed images for pt/Anitube

---

src/es/mhdflix/build.gradle
src/es/mhdflix/src/eu/kanade/tachiyomi/animeextension/es/mhdflix/MhdFlix.kt
src/es/mhdflix/src/eu/kanade/tachiyomi/animeextension/es/mhdflix/MhdFlixDto.kt
src/es/mhdflix/src/eu/kanade/tachiyomi/animeextension/es/mhdflix/MhdFlixFilters.kt

Checklist:
Closes https://github.com/Kohi-den/extensions-source/issues/1081

fixt(mhdflix): Add new extractors and update API endpoints for improved media fetching

---

src/es/flixlatam/build.gradle
src/es/flixlatam/src/eu/kanade/tachiyomi/animeextension/es/flixlatam/FlixLatam.kt

Checklist:
Closes https://github.com/Kohi-den/extensions-source/issues/1075

Fix(flixlatam): Enhance video extraction and link decryption methods
